[package]
name = "project-template-macros"
version = "0.1.0"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
description = "A project template for the quick instantiation of rust projects."
repository = "https://github.com/brace-rs/project-template"
license = "MIT OR Apache-2.0"
edition = "2021"
