name: CI

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    name: Test (${{ matrix.label }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - label: Linux
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          os: ubuntu-latest

        - label: macOS
          target: x86_64-apple-darwin
          toolchain: stable
          os: macos-latest

        - label: Windows
          target: x86_64-pc-windows-msvc
          toolchain: stable
          os: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: dtolnay/rust-toolchain@master
      with:
        targets: ${{ matrix.target }}
        toolchain: ${{ matrix.toolchain }}

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Test
      run: cargo test --target ${{ matrix.target }}
      shell: bash

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: dtolnay/rust-toolchain@master
      with:
        targets: x86_64-unknown-linux-gnu
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Rustfmt
      run: cargo fmt -- --check
      shell: bash

    - name: Clippy
      run: cargo clippy -- -D warnings
      shell: bash

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: dtolnay/rust-toolchain@master
      with:
        targets: x86_64-unknown-linux-gnu
        toolchain: stable

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Install
      uses: taiki-e/install-action@v1
      with:
        tool: cargo-tarpaulin

    - name: Generate
      run: cargo tarpaulin --ignore-tests --skip-clean --out Xml
      shell: bash

    - name: Upload
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
