name: Prepare

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        type: choice
        options:
        - project-template
        - project-template-macros

      bump:
        description: Version to bump
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pull-requests: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Gitsign
      uses: chainguard-dev/actions/setup-gitsign@main

    - name: Install
      uses: taiki-e/install-action@v1
      with:
        tool: cargo-release

    - id: config
      name: Config
      run: |
        name="${{ github.event.inputs.package }}"
        repo="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
        short="${name#$repo-}"

        if [[ "$short" == "$name" ]]; then
          branch="release"
          title="Release"
        else
          branch="release/$short"
          title="Release $short"
        fi

        echo "::set-output name=branch::$branch"
        echo "::set-output name=title::$title"
      shell: bash

    - name: Create Pull Request
      uses: cargo-bins/release-pr@v1
      with:
        version: ${{ github.event.inputs.bump }}
        crate-name: ${{ github.event.inputs.package }}
        branch-prefix: ${{ steps.config.outputs.branch }}
        pr-title: ${{ steps.config.outputs.title }} <%= version.actual %>
        pr-label: release
        pr-template: |
          Creates a new release.

          This is an automated pull request generated by the [prepare][1] workflow.

          [1]: https://github.com/dbalcomb/project-template/blob/main/.github/workflows/prepare.yml
        github-token: ${{ secrets.GITHUB_TOKEN }}
